FROM ubuntu:20.04
RUN apt-get update && apt install -y build-essential patchelf python3 python3-dev python3-dev python3-pip python-is-python3
RUN python3 -m pip install --upgrade pip setuptools wheel
COPY ./ ./
RUN python3 -m pip install -e .
RUN python3 -m pip install nuitka
RUN python -m nuitka --follow-imports --standalone --onefile scripts/nuitka/trampoline.py -o csvbase-client
