name: Tests
on:
  push:
    branches:
      - main
      - '*.x'
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'
  pull_request:
    branches:
      - main
      - '*.x'
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'
jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: Linux, python: '3.10', os: ubuntu-latest, tox: py310}
          # - {name: Windows, python: '3.11', os: windows-latest, tox: py311}
          # - {name: Mac, python: '3.11', os: macos-latest, tox: py311}
          # - {name: '3.12-dev', python: '3.12-dev', os: ubuntu-latest, tox: py312}
          # - {name: '3.10', python: '3.10', os: ubuntu-latest, tox: py310}
          # - {name: '3.9', python: '3.9', os: ubuntu-latest, tox: py39}
          # - {name: '3.8', python: '3.8', os: ubuntu-latest, tox: py38}
          # - {name: '3.7', python: '3.7', os: ubuntu-latest, tox: py37}
          # - {name: 'PyPy', python: 'pypy-3.9', os: ubuntu-latest, tox: pypy39}
          # - {name: 'Pallets Minimum Versions', python: '3.11', os: ubuntu-latest, tox: py311-min}
          # - {name: 'Pallets Development Versions', python: '3.7', os: ubuntu-latest, tox: py37-dev}
          # - {name: Typing, python: '3.11', os: ubuntu-latest, tox: typing}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install required ubuntu packages
        run: sudo apt-get update && sudo apt-get install -y libsystemd-dev postgresql-client python3-dev
      - name: update pip
        run: |
          pip install -U wheel
          pip install -U setuptools
          python -m pip install -U pip
      - run: pip install tox
      - run: tox run -e ${{ matrix.tox }}
